### PR TITLE
ContextAwareCompletableFuture: Fix timing issue

### LINKED ISSUE #55: Timing issue in ContextAwareCompletableFuture?
In production code for a client, there seems to be a deadlock situation with the new `0.5.0` version of the `ContextAwareCompletableFuture` class in combination with calling thenApply and thenCombine in background threads.

I will create a new Pull Request for a unit test that reproduces the issue (and after that, attempt to fix it, obviously).

### PR DESCRIPTION
**Pull request by sjoerdtalsma**
- [x] Add test that reproduces the issue
 - [x] Fix the issue
 - [x] Review the fix
 - [ ] Merge, this resolves #55

### CODE REVIEW

File: context-propagation-java5/src/main/java/nl/talsmasoftware/context/delegation/WrapperWithContext.java [hunk 1]
```diff
@@ -24,36 +24,84 @@
...
+    }
+
+    /**
+     * Calls the supplier for the context snapshot, making sure it is called only once for this wrapper instance.
+     *
+     * @return The snapshot value.
+     */
+    protected ContextSnapshot snapshot() {
+        // Note: Double-checked locking works fine in decent JDKs
+        if (_snapshot == null) synchronized (this) {
```
Comment (yveshan) [inline context-propagation-java5/src/main/java/nl/talsmasoftware/context/delegation/WrapperWithContext.java]: Is it possible to use an AtomicReference::compareAndSet() instead?

File: context-propagation-java8/src/main/java/nl/talsmasoftware/context/functions/BiConsumerWithContext.java [hunk 2]
```diff
@@ -33,20 +33,24 @@
...
+
+    protected BiConsumerWithContext(Supplier<ContextSnapshot> supplier, BiConsumer<T, U> delegate, Consumer<ContextSnapshot> consumer) {
+        super(supplier, delegate, consumer);
     }
 
     @Override
     public void accept(T t, U u) {
-        try (Context<Void> context = snapshot.reactivate()) {
+        try (Context<Void> context = snapshot().reactivate()) {
             try {
```
Comment (yveshan) [inline context-propagation-java8/src/main/java/nl/talsmasoftware/context/functions/BiConsumerWithContext.java]: Is it possible to use only one 'try'?

File: context-propagation-java5/src/main/java/nl/talsmasoftware/context/delegation/WrapperWithContext.java (hunk 1 above)
Comment (sjoerdtalsma) [reply context-propagation-java5/src/main/java/nl/talsmasoftware/context/delegation/WrapperWithContext.java]: AtomicReference's `compareAndSet` requires an evaluated value, which means that in a race condition my guarantee that the `Supplier` is called only once is violated.  
This concern would be addressed by the `AtomicReference.updateAndGet` method, which was only added in Java 8 unfortunately.

Resorting to double-checked locking is the least complicated way I know of to guarantee the _only once_ promise we make regarding the context snapshot supplier.

File: context-propagation-java8/src/main/java/nl/talsmasoftware/context/functions/BiConsumerWithContext.java (hunk 2 above)
Comment (sjoerdtalsma) [reply context-propagation-java8/src/main/java/nl/talsmasoftware/context/functions/BiConsumerWithContext.java]: Unfortunately not.

We have a requirement that a new snapshot is captured and returned to the caller _after_ the function is called, but _before_ the reactivated context is closed (otherwise there's a good chance that we capture and return an empty snapshot).

The [Oracle documentation](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) explains the ordering of _try-with-resources_ and _finally_ statements:
> Note: A try-with-resources statement can have catch and finally blocks just like an ordinary try statement. In a try-with-resources statement, any catch or finally block is run after the resources declared have been closed.

Therefore, we require both an inner-try for _capturing_ and an outer try for _closing_ (unfortunately).

**Comment by sjoerdtalsma** [comment]
@yveshan Thank you very much for the review and great questions.

They indicate under-documented parts of the code. I'll include links to your questions in relevant places for further details.
